//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_WWWManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.WWWManager), typeof(Manager));
		L.RegFunction("LoadImage", LoadImage);
		L.RegFunction("LoadAndCacheImage", LoadAndCacheImage);
		L.RegFunction("LoadImageFromPath", LoadImageFromPath);
		L.RegFunction("DownLoadImage", DownLoadImage);
		L.RegFunction("LocalDownLoadImage", LocalDownLoadImage);
		L.RegFunction("RequestHttpGET", RequestHttpGET);
		L.RegFunction("RequestHttpPOST", RequestHttpPOST);
		L.RegFunction("StopHttp", StopHttp);
		L.RegFunction("StartHTTPGET", StartHTTPGET);
		L.RegFunction("StartHTTPPOST", StartHTTPPOST);
		L.RegFunction("DownloadAPK", DownloadAPK);
		L.RegFunction("StatrtDownloadAPK", StatrtDownloadAPK);
		L.RegFunction("CreatFile", CreatFile);
		L.RegFunction("InstallAPK", InstallAPK);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.LoadImage(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadAndCacheImage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				obj.LoadAndCacheImage(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				obj.LoadAndCacheImage(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.WWWManager.LoadAndCacheImage");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadImageFromPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			System.Collections.IEnumerator o = obj.LoadImageFromPath(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DownLoadImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
			System.Collections.IEnumerator o = obj.DownLoadImage(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LocalDownLoadImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
			obj.LocalDownLoadImage(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RequestHttpGET(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.RequestHttpGET(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RequestHttpPOST(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.WWWForm arg1 = (UnityEngine.WWWForm)ToLua.CheckObject<UnityEngine.WWWForm>(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.RequestHttpPOST(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopHttp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			obj.StopHttp();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartHTTPGET(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			System.Collections.IEnumerator o = obj.StartHTTPGET(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartHTTPPOST(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.WWWForm arg1 = (UnityEngine.WWWForm)ToLua.CheckObject<UnityEngine.WWWForm>(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			System.Collections.IEnumerator o = obj.StartHTTPPOST(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DownloadAPK(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.DownloadAPK(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StatrtDownloadAPK(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			System.Collections.IEnumerator o = obj.StatrtDownloadAPK(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreatFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			obj.CreatFile(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InstallAPK(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.WWWManager obj = (LuaFramework.WWWManager)ToLua.CheckObject<LuaFramework.WWWManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.InstallAPK(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

