//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_SidConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(LuaFramework.SidConfig));
		L.RegVar("TEST", get_TEST, null);
		L.RegVar("MAIN", get_MAIN, null);
		L.RegVar("XW", get_XW, null);
		L.RegVar("MZ", get_MZ, null);
		L.RegVar("SYZ", get_SYZ, null);
		L.RegVar("ZZB", get_ZZB, null);
		L.RegVar("PCDD_M", get_PCDD_M, null);
		L.RegVar("PCDD_P", get_PCDD_P, null);
		L.RegVar("JJW", get_JJW, null);
		L.RegVar("ZK", get_ZK, null);
		L.RegVar("DDZ", get_DDZ, null);
		L.RegVar("JXY", get_JXY, null);
		L.RegVar("JXW", get_JXW, null);
		L.RegVar("DC", get_DC, null);
		L.RegVar("BBW_PC", get_BBW_PC, null);
		L.RegVar("BBW_M", get_BBW_M, null);
		L.RegVar("YL", get_YL, null);
		L.RegVar("QMM", get_QMM, null);
		L.RegVar("MRZD", get_MRZD, null);
		L.RegVar("XZKJ", get_XZKJ, null);
		L.RegVar("STC", get_STC, null);
		L.RegVar("CZ", get_CZ, null);
		L.RegVar("HLZ", get_HLZ, null);
		L.RegVar("TTZ_PC", get_TTZ_PC, null);
		L.RegVar("LKZ", get_LKZ, null);
		L.RegVar("PPZ", get_PPZ, null);
		L.RegVar("YFL", get_YFL, null);
		L.RegVar("MZZ", get_MZZ, null);
		L.RegVar("DINGDZ", get_DINGDZ, null);
		L.RegVar("DDQW", get_DDQW, null);
		L.RegVar("YZ", get_YZ, null);
		L.RegVar("XQ", get_XQ, null);
		L.RegVar("APPLE", get_APPLE, null);
		L.RegVar("APPLE_OFFICIAL", get_APPLE_OFFICIAL, null);
		L.RegVar("APPLE_DDZ", get_APPLE_DDZ, null);
		L.RegVar("APPLE_BBW", get_APPLE_BBW, null);
		L.RegVar("OPPO", get_OPPO, null);
		L.RegVar("VIVO", get_VIVO, null);
		L.RegVar("PPBYJ", get_PPBYJ, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<LuaFramework.SidConfig>.Check = CheckType;
		StackTraits<LuaFramework.SidConfig>.Push = Push;
	}

	static void Push(IntPtr L, LuaFramework.SidConfig arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(LuaFramework.SidConfig), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TEST(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.TEST);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MAIN(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.MAIN);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_XW(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.XW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.MZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SYZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.SYZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ZZB(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.ZZB);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PCDD_M(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.PCDD_M);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PCDD_P(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.PCDD_P);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_JJW(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.JJW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ZK(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.ZK);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DDZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.DDZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_JXY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.JXY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_JXW(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.JXW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DC(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.DC);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BBW_PC(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.BBW_PC);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BBW_M(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.BBW_M);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_YL(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.YL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QMM(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.QMM);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MRZD(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.MRZD);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_XZKJ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.XZKJ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_STC(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.STC);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.CZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HLZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.HLZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TTZ_PC(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.TTZ_PC);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LKZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.LKZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PPZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.PPZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_YFL(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.YFL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MZZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.MZZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DINGDZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.DINGDZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DDQW(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.DDQW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_YZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.YZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_XQ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.XQ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_APPLE(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.APPLE);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_APPLE_OFFICIAL(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.APPLE_OFFICIAL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_APPLE_DDZ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.APPLE_DDZ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_APPLE_BBW(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.APPLE_BBW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OPPO(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.OPPO);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VIVO(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.VIVO);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PPBYJ(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.SidConfig.PPBYJ);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		LuaFramework.SidConfig o = (LuaFramework.SidConfig)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

