//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_ChannelTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(LuaFramework.ChannelType));
		L.RegVar("TEST", get_TEST, null);
		L.RegVar("TEST_MZBY", get_TEST_MZBY, null);
		L.RegVar("TDBY", get_TDBY, null);
		L.RegVar("WZBY", get_WZBY, null);
		L.RegVar("MZBY", get_MZBY, null);
		L.RegVar("DBBY", get_DBBY, null);
		L.RegVar("DFBY", get_DFBY, null);
		L.RegVar("TEST_DFBY", get_TEST_DFBY, null);
		L.RegVar("FKBY", get_FKBY, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<LuaFramework.ChannelType>.Check = CheckType;
		StackTraits<LuaFramework.ChannelType>.Push = Push;
	}

	static void Push(IntPtr L, LuaFramework.ChannelType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(LuaFramework.ChannelType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TEST(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.TEST);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TEST_MZBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.TEST_MZBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TDBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.TDBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WZBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.WZBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MZBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.MZBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DBBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.DBBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DFBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.DFBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TEST_DFBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.TEST_DFBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FKBY(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ChannelType.FKBY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		LuaFramework.ChannelType o = (LuaFramework.ChannelType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

