//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_SDKManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.SDKManager), typeof(Manager));
		L.RegFunction("Start", Start);
		L.RegFunction("SDKInit", SDKInit);
		L.RegFunction("CommonInit", CommonInit);
		L.RegFunction("GetIMEI", GetIMEI);
		L.RegFunction("GetIDFA", GetIDFA);
		L.RegFunction("GetUUID", GetUUID);
		L.RegFunction("GetStoreID", GetStoreID);
		L.RegFunction("OpenAlbum", OpenAlbum);
		L.RegFunction("OpenPhoto", OpenPhoto);
		L.RegFunction("CopyTextToClipboard", CopyTextToClipboard);
		L.RegFunction("JumpToWX", JumpToWX);
		L.RegFunction("InstallAPK", InstallAPK);
		L.RegFunction("OpenWebView", OpenWebView);
		L.RegFunction("Alipay", Alipay);
		L.RegFunction("WechatPay", WechatPay);
		L.RegFunction("WechatLogin", WechatLogin);
		L.RegFunction("InAppPurchases", InAppPurchases);
		L.RegFunction("WechatShareWebpage", WechatShareWebpage);
		L.RegFunction("PostImage", PostImage);
		L.RegFunction("PostToUrl", PostToUrl);
		L.RegFunction("LoadTextureFromLocal", LoadTextureFromLocal);
		L.RegFunction("NativeErrorCallback", NativeErrorCallback);
		L.RegFunction("IEMICallback", IEMICallback);
		L.RegFunction("IDFACallback", IDFACallback);
		L.RegFunction("GetImage", GetImage);
		L.RegFunction("GetWXLogin", GetWXLogin);
		L.RegFunction("GetInAppPurchasesCallback", GetInAppPurchasesCallback);
		L.RegFunction("UrlCallbcak", UrlCallbcak);
		L.RegFunction("OPPOLogin", OPPOLogin);
		L.RegFunction("OPPOLoginCallback", OPPOLoginCallback);
		L.RegFunction("OPPOPay", OPPOPay);
		L.RegFunction("OPPOPayCallback", OPPOPayCallback);
		L.RegFunction("OPPOExit", OPPOExit);
		L.RegFunction("OPPOExitCallback", OPPOExitCallback);
		L.RegFunction("VIVOLogin", VIVOLogin);
		L.RegFunction("VIVOLoginCallback", VIVOLoginCallback);
		L.RegFunction("VIVOWXPay", VIVOWXPay);
		L.RegFunction("VIVOAliPay", VIVOAliPay);
		L.RegFunction("VIVOPayCallback", VIVOPayCallback);
		L.RegFunction("VIVOExit", VIVOExit);
		L.RegFunction("VIVOExitCallback", VIVOExitCallback);
		L.RegFunction("IAppPayWXPay", IAppPayWXPay);
		L.RegFunction("IAppPayAliPay", IAppPayAliPay);
		L.RegFunction("IAppPayPayCallback", IAppPayPayCallback);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("appLinkUrl", get_appLinkUrl, set_appLinkUrl);
		L.RegVar("AFInit", get_AFInit, set_AFInit);
		L.RegVar("UmengInit", get_UmengInit, set_UmengInit);
		L.RegVar("GetIMEICallback", get_GetIMEICallback, set_GetIMEICallback);
		L.RegVar("GetIDFACallback", get_GetIDFACallback, set_GetIDFACallback);
		L.RegVar("GetImageCallBack", get_GetImageCallBack, set_GetImageCallBack);
		L.RegVar("onMessageReceived", get_onMessageReceived, set_onMessageReceived);
		L.RegVar("GetWXLoginCallback", get_GetWXLoginCallback, set_GetWXLoginCallback);
		L.RegVar("InAppPurchasesCallback", get_InAppPurchasesCallback, set_InAppPurchasesCallback);
		L.RegVar("LuaOPPOLoginCallback", get_LuaOPPOLoginCallback, set_LuaOPPOLoginCallback);
		L.RegVar("LuaOPPOPayCallback", get_LuaOPPOPayCallback, set_LuaOPPOPayCallback);
		L.RegVar("LuaOPPOExitCallback", get_LuaOPPOExitCallback, set_LuaOPPOExitCallback);
		L.RegVar("LuaVIVOLoginCallback", get_LuaVIVOLoginCallback, set_LuaVIVOLoginCallback);
		L.RegVar("LuaVIVOPayCallback", get_LuaVIVOPayCallback, set_LuaVIVOPayCallback);
		L.RegVar("LuaVIVOExitCallback", get_LuaVIVOExitCallback, set_LuaVIVOExitCallback);
		L.RegVar("LuaIAppPayPayCallback", get_LuaIAppPayPayCallback, set_LuaIAppPayPayCallback);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.Start();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SDKInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.SDKInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CommonInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.CommonInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetIMEI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.GetIMEI(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetIDFA(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.GetIDFA(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUUID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string o = obj.GetUUID();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStoreID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string o = obj.GetStoreID();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenAlbum(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OpenAlbum(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenPhoto(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OpenPhoto(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyTextToClipboard(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.CopyTextToClipboard(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int JumpToWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.JumpToWX();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InstallAPK(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.InstallAPK(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenWebView(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.OpenWebView(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Alipay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.Alipay(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WechatPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			obj.WechatPay(arg0, arg1, arg2, arg3, arg4);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WechatLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.WechatLogin(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InAppPurchases(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.InAppPurchases(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WechatShareWebpage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			obj.WechatShareWebpage(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PostImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Sprite arg1 = (UnityEngine.Sprite)ToLua.CheckObject(L, 3, typeof(UnityEngine.Sprite));
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			LuaFunction arg4 = ToLua.CheckLuaFunction(L, 6);
			obj.PostImage(arg0, arg1, arg2, arg3, arg4);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PostToUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.WWWForm arg1 = (UnityEngine.WWWForm)ToLua.CheckObject<UnityEngine.WWWForm>(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			System.Collections.IEnumerator o = obj.PostToUrl(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadTextureFromLocal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.Action<UnityEngine.Texture2D> arg1 = (System.Action<UnityEngine.Texture2D>)ToLua.CheckDelegate<System.Action<UnityEngine.Texture2D>>(L, 3);
			System.Collections.IEnumerator o = obj.LoadTextureFromLocal(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int NativeErrorCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.NativeErrorCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IEMICallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.IEMICallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IDFACallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.IDFACallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.GetImage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWXLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.GetWXLogin(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInAppPurchasesCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.GetInAppPurchasesCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UrlCallbcak(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.UrlCallbcak(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OPPOLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OPPOLogin(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OPPOLoginCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OPPOLoginCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OPPOPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 8);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			string arg5 = ToLua.CheckString(L, 7);
			LuaFunction arg6 = ToLua.CheckLuaFunction(L, 8);
			obj.OPPOPay(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OPPOPayCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OPPOPayCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OPPOExit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OPPOExit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OPPOExitCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OPPOExitCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int VIVOLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.VIVOLogin(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int VIVOLoginCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.VIVOLoginCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int VIVOWXPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			LuaFunction arg5 = ToLua.CheckLuaFunction(L, 7);
			obj.VIVOWXPay(arg0, arg1, arg2, arg3, arg4, arg5);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int VIVOAliPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			LuaFunction arg5 = ToLua.CheckLuaFunction(L, 7);
			obj.VIVOAliPay(arg0, arg1, arg2, arg3, arg4, arg5);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int VIVOPayCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.VIVOPayCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int VIVOExit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.VIVOExit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int VIVOExitCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.VIVOExitCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IAppPayWXPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.IAppPayWXPay(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IAppPayAliPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.IAppPayAliPay(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IAppPayPayCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.IAppPayPayCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_appLinkUrl(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			string ret = obj.appLinkUrl;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index appLinkUrl on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AFInit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			bool ret = obj.AFInit;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AFInit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UmengInit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			bool ret = obj.UmengInit;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UmengInit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetIMEICallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.GetIMEICallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetIMEICallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetIDFACallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.GetIDFACallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetIDFACallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetImageCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.GetImageCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetImageCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onMessageReceived(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.onMessageReceived;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onMessageReceived on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetWXLoginCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.GetWXLoginCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetWXLoginCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InAppPurchasesCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.InAppPurchasesCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index InAppPurchasesCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaOPPOLoginCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.LuaOPPOLoginCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaOPPOLoginCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaOPPOPayCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.LuaOPPOPayCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaOPPOPayCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaOPPOExitCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.LuaOPPOExitCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaOPPOExitCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaVIVOLoginCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.LuaVIVOLoginCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaVIVOLoginCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaVIVOPayCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.LuaVIVOPayCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaVIVOPayCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaVIVOExitCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.LuaVIVOExitCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaVIVOExitCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaIAppPayPayCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaInterface.LuaFunction ret = obj.LuaIAppPayPayCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaIAppPayPayCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_appLinkUrl(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.appLinkUrl = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index appLinkUrl on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AFInit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.AFInit = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AFInit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UmengInit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.UmengInit = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UmengInit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GetIMEICallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.GetIMEICallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetIMEICallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GetIDFACallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.GetIDFACallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetIDFACallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GetImageCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.GetImageCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetImageCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onMessageReceived(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.onMessageReceived = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onMessageReceived on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GetWXLoginCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.GetWXLoginCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetWXLoginCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_InAppPurchasesCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.InAppPurchasesCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index InAppPurchasesCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaOPPOLoginCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaOPPOLoginCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaOPPOLoginCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaOPPOPayCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaOPPOPayCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaOPPOPayCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaOPPOExitCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaOPPOExitCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaOPPOExitCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaVIVOLoginCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaVIVOLoginCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaVIVOLoginCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaVIVOPayCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaVIVOPayCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaVIVOPayCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaVIVOExitCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaVIVOExitCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaVIVOExitCallback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaIAppPayPayCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaIAppPayPayCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaIAppPayPayCallback on a nil value");
		}
	}
}

